# ===============================
# DEV keskkond - lokaalne PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
spring.datasource.username=postgres
spring.datasource.password=root
